repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
      - id: black
        args: [ --line-length=100 ]
  - repo: http://github.com/myint/docformatter
    rev: v1.4
    hooks:
      - id: docformatter
        args: [ --wrap-summaries=100, --wrap-descriptions=100 ]
  - repo: https://github.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.910
    files: expyct/
    hooks:
      - id: mypy
        args: [ expyct ]
        pass_filenames: false
        additional_dependencies: [types-backports]
