# This workflow will build docs with Sphinx and deploy them to Github pages
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Build & Publish Docs

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
#  workflow_run:
#    workflows: ["Test"]
#    types:
#      - completed

jobs:
  docs-build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dev requirements
      run: |
        pip install -r dev_requirements.txt
    - name: Build docs
      run: |
        cd docs/ && make html
    - uses: actions/upload-artifact@v2
      with:
        name: docs
        path: docs/_build

  docs-deploy:
    needs: docs-build

    runs-on: ubuntu-latest

    steps:
    - uses: actions/download-artifact@v2
      with:
        name: docs
    - name: Set up Python
      uses: actions/setup-node@v2
      with:
        node-version: 8.10.0
    - name: Disable jekyll builds
      run: touch docs/_build/html/.nojekyll
    - name: Install dependencies
      run: |
        npm install -g --silent gh-pages@2.0.1
    - name: Configure git
      run: |
        git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Deploy docs to gh-pages branch
      run: gh-pages --dotfiles u "github-actions-bot <support+actions@github.com>" --message "[skip ci] Updates" --dist docs/_build/html
