# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Build & Publish Docs

on:
  push:
  pull_request:
#  workflow_run:
#    workflows: ["Test"]
#    types:
#      - completed

jobs:
  docs-build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dev requirements
      run: |
        pip install -r dev_requirements.txt
    - name: Build docs
      run: |
        cd docs/ && make html
    - uses: actions/upload-artifact@v2
      with:
        name: docs
        path: docs/_build

  docs-deploy:
    needs: build

    steps:
    - uses: actions/download-artifact@v2
      with:
        name: docs
    - name: Set up Python
      uses: actions/setup-node@v2
      with:
        node-version: 8.10.0
    - name: Disable jekyll builds
      run: touch docs/_build/html/.nojekyll
    - name: Install and configure dependencies
      run: |
        npm install -g --silent gh-pages@2.0.1
        git config user.email "ci-build@hummingbirdtech.com"
        git config user.name "ci-build"
    - name: Deploy docs to gh-pages branch
      run: gh-pages --dotfiles --message "[skip ci] Updates" --dist docs/_build/html
